import = ["~/.config/alacritty/themes/everforest.toml"]

[window]
dimensions = { columns = 120, lines = 30 }
opacity = 1
dynamic_padding = true
option_as_alt = "Both"
blur = true
decorations = "Buttonless"
title = "Hola"
dynamic_title = false

[font]
normal = { family = "UbuntuSansMono NF", style = "Regular" }
size = 16

[env]
SHELL = "/opt/homebrew/bin/nu"
TERM = "xterm-256color"
